### ISSUE TITLE
Make null resolve to null

### ISSUE THREAD

**Issue by benderTheCrime** [treycordova/jsxdom#2]
Hey there @treycordova, I have a fork of your repo I'm working off of, maybe you can help me implement this https://facebook.github.io/react/blog/2014/07/17/react-v0.11.html#rendering-to-null or implement it in this repo so I can pull it in.

**Comment by treycordova** [comment]
Hey, @benderTheCrime! I've got a draft up and running in master. (See 89d51a54f212ecb93826a3365e8ce3b4428c11b4). Let me know if its output is what you expect to happen. I'm beginning to wonder if `appendChildren` should be used instead of a `<noscript>`. `appendChildren` could be changed to handle a wider amount of cases, like `null`.

**Comment by benderTheCrime** [comment]
Looks like that does it!
